CREATE TABLE IF NOT EXISTS items
(
    id    SERIAL PRIMARY KEY ,
    volume  INTEGER NOT NULL ,
    value INTEGER NOT NULL ,
    art BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS locations
(
    id    SERIAL PRIMARY KEY ,
    ratemin  INTEGER NOT NULL ,
    ratemax  INTEGER NOT NULL
);